/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ReliefChain {
      
    export type CampaignStruct = {campaignId: BytesLike, creator: AddressLike, metadataHash: string, createdAt: BigNumberish, verified: boolean, exists: boolean}

    export type CampaignStructOutput = [campaignId: string, creator: string, metadataHash: string, createdAt: bigint, verified: boolean, exists: boolean] & {campaignId: string, creator: string, metadataHash: string, createdAt: bigint, verified: boolean, exists: boolean }
  

    export type DistributionStruct = {distributionId: BytesLike, batchId: BytesLike, beneficiaryHash: BytesLike, item: string, quantity: BigNumberish, timestamp: BigNumberish, recordedBy: AddressLike, exists: boolean}

    export type DistributionStructOutput = [distributionId: string, batchId: string, beneficiaryHash: string, item: string, quantity: bigint, timestamp: bigint, recordedBy: string, exists: boolean] & {distributionId: string, batchId: string, beneficiaryHash: string, item: string, quantity: bigint, timestamp: bigint, recordedBy: string, exists: boolean }
  

    export type DonationStruct = {donationId: BytesLike, campaignId: BytesLike, amount: BigNumberish, timestamp: BigNumberish, exists: boolean}

    export type DonationStructOutput = [donationId: string, campaignId: string, amount: bigint, timestamp: bigint, exists: boolean] & {donationId: string, campaignId: string, amount: bigint, timestamp: bigint, exists: boolean }
  

    export type ExpenseProofStruct = {expenseId: BytesLike, campaignId: BytesLike, evidenceHash: BytesLike, timestamp: BigNumberish, verified: boolean, exists: boolean}

    export type ExpenseProofStructOutput = [expenseId: string, campaignId: string, evidenceHash: string, timestamp: bigint, verified: boolean, exists: boolean] & {expenseId: string, campaignId: string, evidenceHash: string, timestamp: bigint, verified: boolean, exists: boolean }
  

    export type FundAllocationStruct = {allocationId: BytesLike, campaignId: BytesLike, amount: BigNumberish, timestamp: BigNumberish, exists: boolean}

    export type FundAllocationStructOutput = [allocationId: string, campaignId: string, amount: bigint, timestamp: bigint, exists: boolean] & {allocationId: string, campaignId: string, amount: bigint, timestamp: bigint, exists: boolean }
  

    export type ReliefBatchStruct = {batchId: BytesLike, campaignId: BytesLike, batchCode: string, item: string, quantity: BigNumberish, timestamp: BigNumberish, location: BigNumberish, exists: boolean}

    export type ReliefBatchStructOutput = [batchId: string, campaignId: string, batchCode: string, item: string, quantity: bigint, timestamp: bigint, location: bigint, exists: boolean] & {batchId: string, campaignId: string, batchCode: string, item: string, quantity: bigint, timestamp: bigint, location: bigint, exists: boolean }
  

    export type VerificationStruct = {entityId: BytesLike, entityType: BytesLike, verificationHash: BytesLike, timestamp: BigNumberish, auditor: AddressLike, exists: boolean}

    export type VerificationStructOutput = [entityId: string, entityType: string, verificationHash: string, timestamp: bigint, auditor: string, exists: boolean] & {entityId: string, entityType: string, verificationHash: string, timestamp: bigint, auditor: string, exists: boolean }
  
    }

  export interface ReliefChainInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "AUDITOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "NGO_ROLE" | "SYSTEM_ROLE" | "createCampaign" | "createReliefBatch" | "getCampaign" | "getDistribution" | "getDonation" | "getExpenseProof" | "getFundAllocation" | "getReliefBatch" | "getRoleAdmin" | "getVerification" | "grantAuditorRole" | "grantNgoRole" | "grantRole" | "grantSystemRole" | "hasRole" | "recordDistribution" | "recordDonation" | "recordExpenseProof" | "recordFundAllocation" | "recordVerification" | "renounceRole" | "revokeAuditorRole" | "revokeNgoRole" | "revokeRole" | "revokeSystemRole" | "supportsInterface" | "transferReliefBatch" | "verifyCampaign" | "verifyExpense"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AidDistributed" | "BatchTransferred" | "CampaignCreated" | "CampaignVerified" | "DonationReceived" | "ExpenseRecorded" | "ExpenseVerified" | "FundAllocated" | "ReliefBatchCreated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "VerificationRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'AUDITOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'NGO_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SYSTEM_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'createReliefBatch', values: [BytesLike, BytesLike, string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaign', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getDistribution', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getDonation', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getExpenseProof', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getFundAllocation', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getReliefBatch', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getVerification', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantAuditorRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantNgoRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'grantSystemRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'recordDistribution', values: [BytesLike, BytesLike, BytesLike, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordDonation', values: [BytesLike, BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordExpenseProof', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'recordFundAllocation', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordVerification', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeAuditorRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeNgoRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeSystemRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferReliefBatch', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyCampaign', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyExpense', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'AUDITOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'NGO_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SYSTEM_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createReliefBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDistribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getExpenseProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFundAllocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReliefBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVerification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAuditorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantNgoRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantSystemRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDistribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDonation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordExpenseProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordFundAllocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordVerification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAuditorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeNgoRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeSystemRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferReliefBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyExpense', data: BytesLike): Result;
  }

  
    export namespace AidDistributedEvent {
      export type InputTuple = [distributionId: BytesLike, batchId: BytesLike, beneficiaryHash: BytesLike, item: string, quantity: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [distributionId: string, batchId: string, beneficiaryHash: string, item: string, quantity: bigint, timestamp: bigint];
      export interface OutputObject {distributionId: string, batchId: string, beneficiaryHash: string, item: string, quantity: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchTransferredEvent {
      export type InputTuple = [batchId: BytesLike, fromLocation: BigNumberish, toLocation: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, fromLocation: bigint, toLocation: bigint, timestamp: bigint];
      export interface OutputObject {batchId: string, fromLocation: bigint, toLocation: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignCreatedEvent {
      export type InputTuple = [campaignId: BytesLike, creator: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [campaignId: string, creator: string, timestamp: bigint];
      export interface OutputObject {campaignId: string, creator: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignVerifiedEvent {
      export type InputTuple = [campaignId: BytesLike, verifier: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [campaignId: string, verifier: string, timestamp: bigint];
      export interface OutputObject {campaignId: string, verifier: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DonationReceivedEvent {
      export type InputTuple = [campaignId: BytesLike, donationId: BytesLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [campaignId: string, donationId: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {campaignId: string, donationId: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExpenseRecordedEvent {
      export type InputTuple = [expenseId: BytesLike, campaignId: BytesLike, evidenceHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [expenseId: string, campaignId: string, evidenceHash: string, timestamp: bigint];
      export interface OutputObject {expenseId: string, campaignId: string, evidenceHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExpenseVerifiedEvent {
      export type InputTuple = [expenseId: BytesLike, auditor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [expenseId: string, auditor: string, timestamp: bigint];
      export interface OutputObject {expenseId: string, auditor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundAllocatedEvent {
      export type InputTuple = [campaignId: BytesLike, allocationId: BytesLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [campaignId: string, allocationId: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {campaignId: string, allocationId: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReliefBatchCreatedEvent {
      export type InputTuple = [batchId: BytesLike, campaignId: BytesLike, batchCode: string, item: string, quantity: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, campaignId: string, batchCode: string, item: string, quantity: bigint, timestamp: bigint];
      export interface OutputObject {batchId: string, campaignId: string, batchCode: string, item: string, quantity: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VerificationRecordedEvent {
      export type InputTuple = [entityId: BytesLike, entityType: BytesLike, verificationHash: BytesLike, auditor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [entityId: string, entityType: string, verificationHash: string, auditor: string, timestamp: bigint];
      export interface OutputObject {entityId: string, entityType: string, verificationHash: string, auditor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReliefChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReliefChain;
    waitForDeployment(): Promise<this>;

    interface: ReliefChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    AUDITOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    NGO_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SYSTEM_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [campaignId: BytesLike, metadataHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    createReliefBatch: TypedContractMethod<
      [batchId: BytesLike, campaignId: BytesLike, batchCode: string, item: string, quantity: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCampaign: TypedContractMethod<
      [campaignId: BytesLike, ],
      [ReliefChain.CampaignStructOutput],
      'view'
    >
    

    
    getDistribution: TypedContractMethod<
      [distributionId: BytesLike, ],
      [ReliefChain.DistributionStructOutput],
      'view'
    >
    

    
    getDonation: TypedContractMethod<
      [donationId: BytesLike, ],
      [ReliefChain.DonationStructOutput],
      'view'
    >
    

    
    getExpenseProof: TypedContractMethod<
      [expenseId: BytesLike, ],
      [ReliefChain.ExpenseProofStructOutput],
      'view'
    >
    

    
    getFundAllocation: TypedContractMethod<
      [allocationId: BytesLike, ],
      [ReliefChain.FundAllocationStructOutput],
      'view'
    >
    

    
    getReliefBatch: TypedContractMethod<
      [batchId: BytesLike, ],
      [ReliefChain.ReliefBatchStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getVerification: TypedContractMethod<
      [entityId: BytesLike, ],
      [ReliefChain.VerificationStructOutput],
      'view'
    >
    

    
    grantAuditorRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantNgoRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantSystemRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    recordDistribution: TypedContractMethod<
      [distributionId: BytesLike, batchId: BytesLike, beneficiaryHash: BytesLike, item: string, quantity: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordDonation: TypedContractMethod<
      [campaignId: BytesLike, donationId: BytesLike, amount: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordExpenseProof: TypedContractMethod<
      [expenseId: BytesLike, campaignId: BytesLike, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    recordFundAllocation: TypedContractMethod<
      [campaignId: BytesLike, allocationId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordVerification: TypedContractMethod<
      [entityId: BytesLike, entityType: BytesLike, verificationHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeAuditorRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeNgoRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeSystemRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferReliefBatch: TypedContractMethod<
      [batchId: BytesLike, toLocation: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifyCampaign: TypedContractMethod<
      [campaignId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyExpense: TypedContractMethod<
      [expenseId: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'AUDITOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'NGO_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SYSTEM_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [campaignId: BytesLike, metadataHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createReliefBatch'): TypedContractMethod<
      [batchId: BytesLike, campaignId: BytesLike, batchCode: string, item: string, quantity: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCampaign'): TypedContractMethod<
      [campaignId: BytesLike, ],
      [ReliefChain.CampaignStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDistribution'): TypedContractMethod<
      [distributionId: BytesLike, ],
      [ReliefChain.DistributionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDonation'): TypedContractMethod<
      [donationId: BytesLike, ],
      [ReliefChain.DonationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getExpenseProof'): TypedContractMethod<
      [expenseId: BytesLike, ],
      [ReliefChain.ExpenseProofStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFundAllocation'): TypedContractMethod<
      [allocationId: BytesLike, ],
      [ReliefChain.FundAllocationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getReliefBatch'): TypedContractMethod<
      [batchId: BytesLike, ],
      [ReliefChain.ReliefBatchStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVerification'): TypedContractMethod<
      [entityId: BytesLike, ],
      [ReliefChain.VerificationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantAuditorRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantNgoRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantSystemRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordDistribution'): TypedContractMethod<
      [distributionId: BytesLike, batchId: BytesLike, beneficiaryHash: BytesLike, item: string, quantity: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordDonation'): TypedContractMethod<
      [campaignId: BytesLike, donationId: BytesLike, amount: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordExpenseProof'): TypedContractMethod<
      [expenseId: BytesLike, campaignId: BytesLike, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordFundAllocation'): TypedContractMethod<
      [campaignId: BytesLike, allocationId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordVerification'): TypedContractMethod<
      [entityId: BytesLike, entityType: BytesLike, verificationHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAuditorRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeNgoRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeSystemRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferReliefBatch'): TypedContractMethod<
      [batchId: BytesLike, toLocation: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyCampaign'): TypedContractMethod<
      [campaignId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyExpense'): TypedContractMethod<
      [expenseId: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AidDistributed'): TypedContractEvent<AidDistributedEvent.InputTuple, AidDistributedEvent.OutputTuple, AidDistributedEvent.OutputObject>;
getEvent(key: 'BatchTransferred'): TypedContractEvent<BatchTransferredEvent.InputTuple, BatchTransferredEvent.OutputTuple, BatchTransferredEvent.OutputObject>;
getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'CampaignVerified'): TypedContractEvent<CampaignVerifiedEvent.InputTuple, CampaignVerifiedEvent.OutputTuple, CampaignVerifiedEvent.OutputObject>;
getEvent(key: 'DonationReceived'): TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
getEvent(key: 'ExpenseRecorded'): TypedContractEvent<ExpenseRecordedEvent.InputTuple, ExpenseRecordedEvent.OutputTuple, ExpenseRecordedEvent.OutputObject>;
getEvent(key: 'ExpenseVerified'): TypedContractEvent<ExpenseVerifiedEvent.InputTuple, ExpenseVerifiedEvent.OutputTuple, ExpenseVerifiedEvent.OutputObject>;
getEvent(key: 'FundAllocated'): TypedContractEvent<FundAllocatedEvent.InputTuple, FundAllocatedEvent.OutputTuple, FundAllocatedEvent.OutputObject>;
getEvent(key: 'ReliefBatchCreated'): TypedContractEvent<ReliefBatchCreatedEvent.InputTuple, ReliefBatchCreatedEvent.OutputTuple, ReliefBatchCreatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'VerificationRecorded'): TypedContractEvent<VerificationRecordedEvent.InputTuple, VerificationRecordedEvent.OutputTuple, VerificationRecordedEvent.OutputObject>;

    filters: {
      
      'AidDistributed(bytes32,bytes32,bytes32,string,uint256,uint256)': TypedContractEvent<AidDistributedEvent.InputTuple, AidDistributedEvent.OutputTuple, AidDistributedEvent.OutputObject>;
      AidDistributed: TypedContractEvent<AidDistributedEvent.InputTuple, AidDistributedEvent.OutputTuple, AidDistributedEvent.OutputObject>;
    

      'BatchTransferred(bytes32,uint8,uint8,uint256)': TypedContractEvent<BatchTransferredEvent.InputTuple, BatchTransferredEvent.OutputTuple, BatchTransferredEvent.OutputObject>;
      BatchTransferred: TypedContractEvent<BatchTransferredEvent.InputTuple, BatchTransferredEvent.OutputTuple, BatchTransferredEvent.OutputObject>;
    

      'CampaignCreated(bytes32,address,uint256)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'CampaignVerified(bytes32,address,uint256)': TypedContractEvent<CampaignVerifiedEvent.InputTuple, CampaignVerifiedEvent.OutputTuple, CampaignVerifiedEvent.OutputObject>;
      CampaignVerified: TypedContractEvent<CampaignVerifiedEvent.InputTuple, CampaignVerifiedEvent.OutputTuple, CampaignVerifiedEvent.OutputObject>;
    

      'DonationReceived(bytes32,bytes32,uint256,uint256)': TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
      DonationReceived: TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
    

      'ExpenseRecorded(bytes32,bytes32,bytes32,uint256)': TypedContractEvent<ExpenseRecordedEvent.InputTuple, ExpenseRecordedEvent.OutputTuple, ExpenseRecordedEvent.OutputObject>;
      ExpenseRecorded: TypedContractEvent<ExpenseRecordedEvent.InputTuple, ExpenseRecordedEvent.OutputTuple, ExpenseRecordedEvent.OutputObject>;
    

      'ExpenseVerified(bytes32,address,uint256)': TypedContractEvent<ExpenseVerifiedEvent.InputTuple, ExpenseVerifiedEvent.OutputTuple, ExpenseVerifiedEvent.OutputObject>;
      ExpenseVerified: TypedContractEvent<ExpenseVerifiedEvent.InputTuple, ExpenseVerifiedEvent.OutputTuple, ExpenseVerifiedEvent.OutputObject>;
    

      'FundAllocated(bytes32,bytes32,uint256,uint256)': TypedContractEvent<FundAllocatedEvent.InputTuple, FundAllocatedEvent.OutputTuple, FundAllocatedEvent.OutputObject>;
      FundAllocated: TypedContractEvent<FundAllocatedEvent.InputTuple, FundAllocatedEvent.OutputTuple, FundAllocatedEvent.OutputObject>;
    

      'ReliefBatchCreated(bytes32,bytes32,string,string,uint256,uint256)': TypedContractEvent<ReliefBatchCreatedEvent.InputTuple, ReliefBatchCreatedEvent.OutputTuple, ReliefBatchCreatedEvent.OutputObject>;
      ReliefBatchCreated: TypedContractEvent<ReliefBatchCreatedEvent.InputTuple, ReliefBatchCreatedEvent.OutputTuple, ReliefBatchCreatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'VerificationRecorded(bytes32,bytes32,bytes32,address,uint256)': TypedContractEvent<VerificationRecordedEvent.InputTuple, VerificationRecordedEvent.OutputTuple, VerificationRecordedEvent.OutputObject>;
      VerificationRecorded: TypedContractEvent<VerificationRecordedEvent.InputTuple, VerificationRecordedEvent.OutputTuple, VerificationRecordedEvent.OutputObject>;
    
    };
  }